name: Keep Render awake
on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 min
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up backend
        run: curl -s https://hospital-management-3y59.onrender.com > /dev/null
