
name: SPA redirect & keep-alive
on:
  push:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Inject _redirects
        run: |
          echo '/*    /index.html   200' > dist/hospitalApp/_redirects

      - name: Deploy to Render
        uses: render-examples/deploy-to-render@v1
        with:
          service-id: srv-d1tsn4er433s73e4djg0   # your static site
          api-key: ${{ secrets.RENDER_API_KEY }}

